export default {
    path:"/movie",
    component:_=>import("@pages/movie"),
    name:"movie",
    meta:{
        flag:true,
        requiredAuth:false
    },
    children:[
        {
            path:"/movie",
            redirect:"/movie/movienow"
        },
        {
            path:"movienow",
            component:_=>import("@components/movienow"),
            name:"movienow",
            meta:{
                flag:true,
                requiredAuth:false
            },
        },
        {
            path:"moviecomming",
            component:_=>import("@components/moviecomming"),
            name:"moviecomming",
            meta:{
                flag:true,
                requiredAuth:false
            },
        }
    ]
}